<?php

namespace Customize\Repository;

use Customize\Entity\ProductFeature;
use Eccube\Repository\AbstractRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ProductFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductFeatureRepository extends AbstractRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ProductFeature::class);
    }
}
