name: Coverage

on:
  workflow_call:

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.3 ]
        db: [ pgsql ]
        include:
          - db: pgsql
            database_url: postgres://postgres:password@127.0.0.1:5432/eccube_db
            database_server_version: 14
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache apt packages for pcov
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: php8.3-pcov
          version: 1.0

      - name: Setup pcov
        run: sudo phpenmod -s cli pcov

      - name: Initialize Composer
        uses: ./.github/actions/composer

      - name: Setup EC-CUBE
        env:
          APP_ENV: 'test'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
        run: |
          bin/console doctrine:database:create
          bin/console doctrine:schema:create
          bin/console eccube:fixtures:load

      - name: PHPUnit
        env:
          APP_ENV: 'test'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          MAILER_URL: 'smtp://127.0.0.1:1025'
        continue-on-error: true
        run: |
          echo "session.save_path=$PWD/var/sessions/test" > php.ini
          echo "memory_limit=512M" >> php.ini
          php -c php.ini -dpcov.enabled=1 vendor/bin/phpunit --exclude-group cache-clear,cache-clear-install,update-schema-doctrine --coverage-clover=coverage1.xml
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage1.xml
          flags: Unit
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
